[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "1.78"
proportional_cost_splitter = { git = "https://github.com/ryanhossain9797/proportional_cost_splitter.git" }
